### PR TITLE
Relax rails dependency to support Rails 5

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by cbeer** [comment]
The build failure appears unrelated; I've submitted either #53 or #54 to try to fix the dependency problem.

**Comment by lukaszsagol** [comment]
🚀

Thank you very much for this one and Travis config changes.

Hope this will speed up your upgrade to Rails 5 :)

**Comment by cbeer** [comment]
@lukaszsagol thanks for merging -- any chance of a 0.5.1 release with the relaxed dependency?

**Comment by lukaszsagol** [comment]
@cbeer https://rubygems.org/gems/sir_trevor_rails/versions/0.5.1 :shipit:

**Comment by cbeer** [comment]
👏

**Pull request merged**
